fix es5 issue
wojtekmaj/react-pdf pull request #794
Opened 2021-06-04 11:31 UTC by njleonzhang

`react-pdf` supports es5 itself, and it‘s dependency `pdfjs-dist` supports es5 in `dist/es5` folder. for entire supporting es5, `react-pdf` should require file in `pdfjs-dist/dist/es5`

2021-06-04 20:05 UTC, wojtekmaj commented
What is the issue we're trying to solve here? Does it crash on any of the supported browsers? Please raise an issue first so we can reproduce and discuss.

2021-06-06 13:13 UTC, njleonzhang commented
> What is the issue we're trying to solve here? Does it crash on any of the supported browsers? Please raise an issue first so we can reproduce and discuss.

Sorry, I have not found the browser list react-pdf supports. According to the document, I can know IE is not supported in v5.

```
// https://unpkg.com/react-pdf@5.3.0/dist/umd/entry.js
...
var pdfjs = _interopRequireWildcard(require("pdfjs-dist"));
...
```
`react-pdf` import `pdfjs-dist` in build code, this cause projects which use `react-pdf` import `pdfjs-dist` indirectly. `react-pdf` is es5 compatible, but `pdfjs-dist` is not  by default.

This causet, it causes the projects which use `react-pdf` crash browsers that do not support es6.

2021-06-28 06:53 UTC, mrbaguvix reviewed
@njleonzhang Have you been able to create an issue and link it to this PR?

2021-06-29 05:39 UTC, njleonzhang commented
@mrbaguvix why we need a issue, it's the process for pr merging?

2021-07-12 09:56 UTC, wojtekmaj commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Please remove.

2021-07-13 02:52 UTC, njleonzhang commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
done @wojtekmaj

2021-07-13 03:20 UTC, wojtekmaj approved these changes

2021-07-15 01:39 UTC, yordis commented
Any idea when it could be release?

2021-07-23 02:36 UTC, njleonzhang commented
any plan to merge and release?

2021-07-27 11:12 UTC, wojtekmaj commented
As of pdfjs-dist 2.9.359 `es5` directory is gone. There is `legacy` directory though.

Not sure how to proceed, as we should really be using non-legacy code here. Perhaps a workaround based on webpack alias might be of any help.

2021-07-28 07:32 UTC, njleonzhang commented
ORZ!! The breaking change is released with a minor version?

2021-07-28 12:20 UTC, wojtekmaj commented
Lol, that's classic PDF.js. Their versions do not follow semver at all. That's the very reason we have `pdfjs-dist`(and only `pdfjs-dist`) version locked.

2021-08-20 18:50 UTC, chinnick967 commented
I'm having this issue https://github.com/wojtekmaj/react-pdf/issues/808 in our project and wanted to see when this PR will be merged and released. Thanks!

2021-08-25 07:00 UTC, wojtekmaj requested changes
Need to rebase off newest `main` and change paths to from /es5 to /legacy

2021-08-30 23:51 UTC, andredantasrocha commented
@njleonzhang Thanks for the changes!!! can't wait to use the new code after the PR is merged :)

2021-09-01 08:57 UTC, merged

2021-09-01 08:57 UTC, wojtekmaj commented
Thanks!

2021-09-01 08:58 UTC, andredantasrocha commented
Amazing! Thanks guys!